import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import "./globals.css";
import ReduxProvider from "./redux/provider/reduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hasin's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
       <ReduxProvider>
        <Toaster/><Navbar/>
          
          
        
        {children}
        </ReduxProvider>
        
        </body>
    </html>
  );
}
